export enum ActionTypes {
  SET_CANDIDATE,
  SET_VISITED_USERS,
  SET_TIME_LEFT,
  SET_TIME_DECREASE,
  SET_USERS_DATA,
  SET_SOCKET_ID,
  SET_CONNECTION_IDS,
  SET_STREAM,
  SET_RECEIVING_CALL,
  SET_CALLER_DATA,
  SET_CONNECTION_ACCEPTED,
  SET_LOADING,
}
